emailTxt        =   "xpath://input[@id='email']"
passwordTxt     =   "xpath://input[@id='password']"
loginBtn        =   "xpath://button[normalize-space()='Login']"
rememCheckBox   =   "xpath://span[@class='aiz-square-check']"
forgotBtn       =   "xpath://a[normalize-space()='Forgot password ?']"
titleCheck      =   "xpath://title[contains(text(),'AT eCommerce | Automation Testing')]"
notAccountTxt   =   "xpath://div[@role='alert']"