navBar                  =   "//div[@class=\"aiz-side-nav-wrap\"]"
addNewCategory          =   "//span[text()=\"Add New category\"]"
categoryInformation     =   "//h5[text()=\"Category Information\"]"
firstEditButton         =   "(//a[@title=\"Edit\"])[1]"
inputButton             =   "//input[@id=\"search\"]"
firstPlusButton         =    "(//span[@class=\"footable-toggle fooicon fooicon-plus\"])[1]"
firstParentCategory     =   "(//tr[@class=\"footable-detail-row\"]/descendant::th[text()=\"Parent Category\"])[1]"
firstDeleteButton       =   "(//a[@title=\"Delete\"])[1]"
feleteModal             =   "(//div[@id=\"delete-modal\"])[1]"
cancelDeleteButton      =   "//div[@class=\"modal-body text-center\"]/descendant::button"
pressDeleteButton       =   "//a[text()=\"Delete\"]"
alertLocation           =   "//div[@role=\"alert\"]"
FeaturedCheckbox        =   "(//label[@class=\"aiz-switch aiz-switch-success mb-0\"])[1]"
pageIndex               =   "//a[@class=\"page-link\"and text()=\"2\"]"
nextPageButton          =   "//a[@class=\"page-link\"and @rel=\"next\"]"
uRLIndex                =   "https://ecommerce.anhtester.com/admin/categories?page=2"