userNameTxt      =   "xpath://*[@id='root']/div/div[2]/div[2]/div[2]/div/div/div/div/form/div/div[1]/div/div/div/div"
userNameListBox  =   "xpath://*[@id='menu-']/div[3]/ul"
passwordTxt      =   "xpath://input[@id='password']"
loginBtn         =   "xpath://button[normalize-space()='Login']"
rememCheckBox    =   "xpath://span[@class='aiz-square-check']"
forgotBtn        =   "xpath://a[normalize-space()='Forgot password ?']"
titleCheck       =   "xpath://title[contains(text(),'AT eCommerce | Automation Testing')]"
notAccountTxt    =   "xpath://div[@role='alert']"