searchTxt       =       "xpath://input[@id='search']"
SearchBtn       =       "xpath://div[@class='input-group-append d-none d-lg-block']//button"
compareBtn      =       "xpath://span[contains(text(),'Compare')]"
wishlistBtn     =       "xpath://span[normalize-space()='Wishlist']"
cartBtn         =       "xpath://span[contains(text(),'Cart')]"
flashSaleBtn    =       "xpath://a[contains(text(),'Flash Sale')]"
logOutBtn       =       "xpath://li[@class='list-inline-item mr-3 border-right border-left-0 pr-3 pl-0']//a"
emailTxt        =       "xpath:(//input[@name='email'])[1]"
subBtn          =       "xpath://button[normalize-space()='Subscribe']"
applyBtn        =       "xpath://a[contains(text(),'Apply Now')]"
homeBtn         =       "xpath://a[contains(text(),'Home')]"
checkPopup      =       "xpath://div[@class='aiz-editor-data']//p//img"
closePop        =       "xpath://i[@class='la la-close fs-20']"
childMenuBtn    =       "xpath://a[normalize-space()='\"Flash deals\"']"