menuProduct     =   "xpath://span[normalize-space()='Products']"
browserBtn      =   "xpath://a[@title='Browse Website']"
clearCacheBtn   =   "xpath://span[@class='fw-500 ml-1 mr-0 d-none d-md-block']"
cacheTxt        =   "xpath://div[@role='alert']"
flagIcon        =   "xpath://span[@class='language']"
productCheck    =   "xpath://h6[normalize-space()='Top 12 Products']"
iconRight       =   "xpath://i[@class='las la-angle-right']"
iconLeft        =   "xpath://i[@class='las la-angle-left']"
searchTxt       =   "xpath://input[@id='menu-search']"